In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action='ignore',category=np.VisibleDeprecationWarning)

## Part 1: Flight data: different sampling regimes ##

In [2]:
united = Table.read_table('united.csv')
united = united.with_column('Row', np.arange(united.num_rows)).move_to_start('Row')
united

Row  | Date   | Flight Number | Destination | Delay
0    | 6/1/15 | 73            | HNL         | 257
1    | 6/1/15 | 217           | EWR         | 28
2    | 6/1/15 | 237           | STL         | -3
3    | 6/1/15 | 250           | SAN         | 0
4    | 6/1/15 | 267           | PHL         | 64
5    | 6/1/15 | 273           | SEA         | -6
6    | 6/1/15 | 278           | SEA         | -8
7    | 6/1/15 | 292           | EWR         | 12
8    | 6/1/15 | 300           | HNL         | 20
9    | 6/1/15 | 317           | IND         | -10
... (13815 rows omitted)

In [3]:
# A deterministic sample
united.where('Destination', 'HNL')

Row  | Date   | Flight Number | Destination | Delay
0    | 6/1/15 | 73            | HNL         | 257
8    | 6/1/15 | 300           | HNL         | 20
35   | 6/1/15 | 663           | HNL         | 4
127  | 6/1/15 | 1670          | HNL         | 3
151  | 6/2/15 | 73            | HNL         | 0
158  | 6/2/15 | 300           | HNL         | 7
232  | 6/2/15 | 1175          | HNL         | 25
275  | 6/2/15 | 1670          | HNL         | 186
297  | 6/3/15 | 73            | HNL         | 354
304  | 6/3/15 | 300           | HNL         | 2
... (455 rows omitted)

In [4]:
# Another deterministic sample:
united.take(np.arange(42, united.num_rows, 100))

Row  | Date   | Flight Number | Destination | Delay
42   | 6/1/15 | 715           | PHX         | -1
142  | 6/1/15 | 1753          | MCO         | 18
242  | 6/2/15 | 1266          | EWR         | 13
342  | 6/3/15 | 721           | DFW         | 154
442  | 6/3/15 | 1922          | EWR         | 144
542  | 6/4/15 | 1453          | SEA         | 0
642  | 6/5/15 | 595           | PDX         | -9
742  | 6/5/15 | 1754          | EWR         | 31
842  | 6/6/15 | 1535          | KOA         | 4
942  | 6/7/15 | 824           | JFK         | -2
... (128 rows omitted)

In [5]:
# A third deterministic sample:
united.take(make_array(15, 30, 35))

Row  | Date   | Flight Number | Destination | Delay
15   | 6/1/15 | 388           | ORD         | -9
30   | 6/1/15 | 577           | EWR         | -9
35   | 6/1/15 | 663           | HNL         | 4

In [6]:
# A random sample: unpack what this code does!
start = np.random.choice(np.arange(100))
systematic_sample = united.take(np.arange(start, united.num_rows, 100))
systematic_sample

Row  | Date   | Flight Number | Destination | Delay
18   | 6/1/15 | 433           | LAX         | 10
118  | 6/1/15 | 1602          | ATL         | 6
218  | 6/2/15 | 1076          | IAD         | 43
318  | 6/3/15 | 477           | ORD         | -4
418  | 6/3/15 | 1634          | BOS         | 10
518  | 6/4/15 | 1120          | IAH         | 12
618  | 6/5/15 | 349           | EWR         | -3
718  | 6/5/15 | 1608          | EWR         | -6
818  | 6/6/15 | 1089          | BOS         | 20
918  | 6/7/15 | 455           | BOS         | -2
... (129 rows omitted)

## Part 2: Your work ##

* What is the longest flight delay in the table?
* What is the average flight delay?
* If you choose 100 random flights using united.sample(100), what is the average delay for those flights?
* Which city has the highest average delay? The lowest?
* Make a histogram of the delays.

In [1]:
# Happy coding!